### ISSUE TITLE
Desenvolver frontend da página de perfil do usuário (Alterar dados)

### ISSUE THREAD

**Issue by pragmaticivan** [RubyCastsBrasil/RubyCastsBrasil#133]
Essa task tem como dependência a issue #132.
Uma vez que o psd for mergeado na master, essa task pode começar a ser feita.

**Comment by plribeiro3000** [comment]
@rrrcompagnoni Pode mandar ver. Agora a gente vai mudar a politíca de assigne. Só passa o assigne quando tiver PR aberto.

**Comment by rrrcompagnoni** [comment]
@plribeiro3000 blza, tem o psd?

**Comment by plribeiro3000** [comment]
Tem sim @rrrcompagnoni . Ta na master do projeto ae dentro da pasta `doc`.

Acredito que o link para o mockup correto seja [esse](https://github.com/RubyCastsBrasil/RubyCastsBrasil/blob/master/doc/mockups/lay-user-edit-informations.psd)

**Comment by rrrcompagnoni** [comment]
@plribeiro3000 tem algum tipo de cache na app?
to modificando o css e não altera no navegador uheheuh :T

**Comment by plribeiro3000** [comment]
@rrrcompagnoni Só o normal do rails. Uma dessas coisas pode te ajudar:

* Reiniciar o servidor Rails
* Parar o servidor Rails, matar o spring e subir o servidor Rails novamente
  * `bin/spring stop`
  * `bin/rails s`
* Parar o servidor Rails, apagar a pasta de cache e subir o servidor Rails novamente
  * `rm -rf tmp/cache`
  * `bin/rails s`

**Comment by rrrcompagnoni** [comment]
apagando a pasta de cache funciona, o problema é que todo crtl+s tem que apagar e subir de novo o servidor

**Comment by plribeiro3000** [comment]
@rrrcompagnoni Estranho. Tenta fechar e abrir o terminal novamente. Tentaste matar o `spring`?

**Comment by rrrcompagnoni** [comment]
@plribeiro3000  opa tudo bom? então tentei mas ele inicia cria a pasta de cache e não atualiza
você consegue ver ai se ta mantendo o cache também?

**Comment by daniloisr** [comment]
@plribeiro3000 estou dando uma olhada nesse problema. :+1:

**Comment by plribeiro3000** [comment]
@daniloisr Vlw.

@rrrcompagnoni Cara, não consegui reproduzir seu erro. =s

**Comment by rrrcompagnoni** [comment]
buenas @plribeiro3000  apenas te dando um feedback
eu to em um intensivo de inglês esse mês kkk
mas to fazendo a página, mesmo que devagar 
UEHUEHU caso precise dela da um toque que eu acho um jeito de terminar, abraço

**Comment by rrrcompagnoni** [comment]
alguém aí sabe como eu passo :vertical_form no simple_form?

**Comment by plribeiro3000** [comment]
Opa @rrrcompagnoni. Talvez o Ivan saiba de dizer com mais certeza.

cc/ @pragmaticivan

**Comment by plribeiro3000** [comment]
Fechada a partir do PR #205 .
