### ISSUE TITLE
Criar psd da página de cadastro de screencasts

### ISSUE THREAD

**Issue by pragmaticivan** [RubyCastsBrasil/RubyCastsBrasil#139]
A página de cadastro de screencasts é uma página de formulário com os seguintes atributos:

* nome: string
* url do vídeo: string
* categoria: um select com as opções
* tags: poderão ser escolhidas várias tags

**Comment by vgsantoniazzi** [comment]
Alguém já desenvolveu? senão passa a bola pra mim!

**Comment by plribeiro3000** [comment]
@vgsantoniazzi Pode mandar ver!

Você abrindo o PR te passo o assigne!

**Comment by rafex128** [comment]
Alguém fez o psd?

**Comment by plribeiro3000** [comment]
@rafex128 Não. Tiver de bobeira pode fazer. =)
