### ISSUE TITLE
Sobre os comentários: usar Disqus ou fazer no braço

### ISSUE THREAD

**Issue by joridos** [RubyCastsBrasil/RubyCastsBrasil#193]
Os comentários poderiamos usar o Disqus pois é mais rápido para publicarmos um MVP e para frente fazermos algo no :muscle: , ou continuamos com o Disqus se for bom, oque acham?

**Comment by juhguu** [comment]
Na minha opinião, o disqus já é uma excelente solução para comentários. Acredito que só seria necessário desenvolver uma outra caso a necessidade do rubycasts fosse muito específica, o que não é o caso.

**Comment by LulzAugusto** [comment]
+1 Disqus :)

**Comment by daniloisr** [comment]
:+1: Disqus

**Comment by plribeiro3000** [comment]
:+1: Disqus

**Comment by rrrcompagnoni** [comment]
todo site usa, todo mundo deve ter conta 
+1

**Comment by plribeiro3000** [comment]
Como todos foram de acordo e ninguém mais se pronunciou nos últimos 3 dias eu declaro essa votação encerrada!

Obrigado a todos que participaram!

**Comment by plribeiro3000** [comment]
Link para a página no wiki: https://github.com/RubyCastsBrasil/RubyCastsBrasil/wiki/Decisoes-Comentarios
