### ISSUE TITLE
Corrigir espaços no HEADER e FOOTER

### ISSUE THREAD

**Issue by hudsonmarinho** [RubyCastsBrasil/RubyCastsBrasil#196]
Acessando o site percebi uma falha no header, um espaço entre o HEADER e o inicio do conteúdo
![captura de tela 2015-01-28 as 10 00 21 am](https://cloud.githubusercontent.com/assets/1214086/5941745/b7c02570-a6f1-11e4-8025-83718615e63f.png)

e no rodapé tem um espaço no final
![captura de tela 2015-01-28 as 10 00 49 am](https://cloud.githubusercontent.com/assets/1214086/5941749/bc8d6950-a6f1-11e4-8102-5962a96e8319.png)

Estou usando o `CHROME`

**Comment by plribeiro3000** [comment]
hmm. Bem levantado @hudsonmarinho. Obrigado pelo seu feedback!

Tu poderia dar uma olhada e tentar resolver isso?

**Comment by hudsonmarinho** [comment]
Posso sim @plribeiro3000 :smile:

**Comment by plribeiro3000** [comment]
Opa. Valeu @hudsonmarinho.

**Comment by kidush** [comment]
e aew galera, alguém já está mexendo?

**Comment by plribeiro3000** [comment]
E aew @kidush. O @hudsonmarinho ficou de dar uma olhada mas se tu tiver de bobeira manda ver. =)

Pra tentar agilizar o processo a gente só vai dar assigne em uma issue quando o PR estiver aberto e aguardando review. =)

**Comment by kidush** [comment]
blza @plribeiro3000  =)

**Comment by hudsonmarinho** [comment]
@kidush ainda não tive tempo para fazer, estou numa correria no projeto da empresa :cry:

**Comment by kidush** [comment]
Opa @hudsonmarinho, hoje eu vejo a noite :smile:

**Comment by pragmaticivan** [comment]
Corrigi isso.
