### ISSUE TITLE
O que acham de dar ignore no arquivo db/schema.rb ?

### ISSUE THREAD

**Issue by pragmaticivan** [RubyCastsBrasil/RubyCastsBrasil#198]
Toda vez que alguém utiliza um banco diferente as vezes ele dar overwrite, seria interessante dar ignore nele.

**Comment by daniloisr** [comment]
O db/schema.rb deve ser versionado, ele carrega a estrutura atual do banco, e muitas vezes é melhor usar um `rake db:schema:load` do que rodar o `rake db:migrate`. Ele deve ser incluido apenas se existir uma migration no pull request.

Nesse caso é o avaliador do pull request pedir um rebase ignorando as mudanças desnecessárias no db/schema. "Other conflicts, like column definition switching locations can easily be avoided by being careful what you commit to the repository." ([resposta no stackoverflow](http://stackoverflow.com/a/6520115))

Veja algumas referências:
[resposta legal no stackoverflow](http://stackoverflow.com/a/6520115)
[conversa muito boa que rolou no facebook/rubyonrailsbrasil](https://www.facebook.com/groups/rubyonrailsbrasil/permalink/675235435937304/)
[+ outra ref, mesma coisa das de cimas](http://www.saturnflyer.com/blog/jim/2010/09/14/always-check-in-schema-rb/)

**Comment by pragmaticivan** [comment]
Nenhum dos links levou em consideração o que eu falei, eu versiono nos meus projetos tbm, porém, nesse caso tem galera usando sqlite3, postgresql, mysql, etc... ele altera esse arquivo, nenhum dos posts da uma solução pra isso, acho que é algo a se considerar.

**Comment by plribeiro3000** [comment]
Então. Acho que a gente ja teve essa discussão antes. Se não me engano la no começo do projeto. Foi aqui: #4.

Como o @daniloisr mesmo mencionou é interessante versionar esse arquivo sim por várias questões. Acho legal o esquema de quem for o avaliador dar uma olhada nisso mas até o presente momento achei um overhead extra dado a quantidade de iterações que a gente tem nos PR's normalmente para atingirmos uma qualidade miníma.

@pragmaticivan @daniloisr Acham interessante adicionar mais um step no [review](https://github.com/RubyCastsBrasil/RubyCastsBrasil/wiki/Fluxo-de-Revisao-de-Codigo)?

**Comment by pragmaticivan** [comment]
Não vai afetar muito, só acho que a cada pr ele vai ficar alterando, desnecessáriamente. Mas rilex :)
