### ISSUE TITLE
Definir Style Guide de SCSS

### ISSUE THREAD

**Issue by plribeiro3000** [RubyCastsBrasil/RubyCastsBrasil#206]
O @houndci tem suporte a revisão de `.scss` agora. Portanto seria interessante a gente decidir um style guide para seguir ou simplesmente seguir o que ele passa e acertar as regras.

Link: https://houndci.com/configuration#scss

cc/ @pragmaticivan

**Comment by plribeiro3000** [comment]
Ninguém tem algo a pronunciar sobre isso?

Se for o caso vou deixar o padrão que o próprio @houndci usa. =s

**Comment by pragmaticivan** [comment]
Rapah, por mim desativaria esse suporte do houndci por agora. É DE IRRITAR, usei em um projeto aqui, a gente tem que finalizar essa budega primeiro.

**Comment by plribeiro3000** [comment]
Hauehauheua. Bom ponto. =)

Em qua, 22 de abr de 2015 22:25, Ivan Santos <notifications@github.com>
escreveu:

**Comment by daniloisr** [comment]
@pragmaticivan kkkkkkk :joy: 

Mas eu curto ele, eu ligaria o lint de css :v:

Acho bom todo mundo codar no mesmo estilo, e como todo repositório grande usa um guia, se o RubyCastsBrasil crescer muito teremos que ter um também. Então o lance é decidir ligar ele agora ou mais tarde.

**Comment by mfbmina** [comment]
O problema de se desligar o Hound é se ninguém pegar pra refatorar depois. Vai ficar tudo uma bagunça. :cry:

**Comment by rrrcompagnoni** [comment]
@mfbmina mandar pro codeclimate não resolve essa treta depois? ueheuhu

**Comment by plribeiro3000** [comment]
@mfbmina @rrrcompagnoni Tem os dois lados. Resolver código lambusado é sempre mais caro que fazer com calma algo mais bem estruturado mas por outro lado estamos correndo para fechar isso.

Eu acho que talvez seja interessante manter ele ativado e conforme for aparecendo as coisas a gente usa do bom senso, se for algo simples de resolver, já resolve na hora se não deixa e tenta não fazer isso da próxima vez. Funciona pra todo mundo assim?

**Comment by mfbmina** [comment]
@plribeiro3000 pode ser.. atende os dois lados. @rrrcompagnoni por experiência minha, prefiro não deixar isso passar. O code climate vai dizer isso, mas até alguem ter a boa vontade de refatorar vai bastante tempo haha

**Comment by rrrcompagnoni** [comment]
Tranquilo, só disse do cm como solução no caso de desligar o hd

**Comment by plribeiro3000** [comment]
É como eu disse. fica bem mais custoso e caro se preocupar com isso depois. Já vi vários projetos serem abandonados e serem refeitos do zero por causa do custo da refatoração. =s

**Comment by joffilyfe** [comment]
Realmente faz mais sentido manter ligado e ir corrigindo o que for necessário durante os PRs.

**Comment by plribeiro3000** [comment]
Ninguém tem nada a adicionar aqui?

**Comment by wenderjean** [comment]
Por mim a gente habilita o lint do css, como tu falou o custo pra se resolver as coisas depois é bem maior. :)

**Comment by plribeiro3000** [comment]
@wenderjean Então é so manter como está. =)

**Comment by plribeiro3000** [comment]
Vou considerar isso como fechado. Ja passou da hora até. hehehe

**Comment by plribeiro3000** [comment]
Decisão Documentada: https://github.com/RubyCastsBrasil/RubyCastsBrasil/wiki/Decisoes-StyleGuide

Sintam se a a vontade para corrigir erros de português ou adicionar algo que esqueci de mencionar. =)
