### ISSUE TITLE
Menu mobile não funciona

### ISSUE THREAD

**Issue by joffilyfe** [RubyCastsBrasil/RubyCastsBrasil#207]
![captura de tela de 2015-04-13 12 28 25](https://cloud.githubusercontent.com/assets/4604104/7123704/628cd3d4-e1fa-11e4-8565-66d887a8377a.png)
 
O menu responsivo não está funcionando, provavelmente tem a ver com o javascript utilizado no menu, não cheguei a ver o código.

**Comment by wenderjean** [comment]
Vou dar um olhada nisso. :)

**Comment by joffilyfe** [comment]
@wenderjean valeu! Eu mesmo iria consertar mas preciso primeiro saber se o menu tem realmente que ser o do bootstrap ou poderia ser um próprio ou de terceiros. Se algum core poder comunicar aqui fica mais fácil ( @plribeiro3000, @pragmaticivan ).

**Comment by plribeiro3000** [comment]
@wenderjean @joffilyfe Acho que não tem muita frescura não. O que concertar ta valendo. Depois se for o caso alguém manda outro PR acertando de uma outra maneira e dae a comunidade discute em cima das duas opções. =)

**Comment by wenderjean** [comment]
Fechou @plribeiro3000. 
@joffilyfe Tu quer fazer ou pode mandar bala?

**Comment by joffilyfe** [comment]
@wenderjean pode fazer, não vou ter tempo imediatamente.

**Comment by wenderjean** [comment]
Blz... :+1:

**Comment by plribeiro3000** [comment]
Fechada pela issue #208.
