### ISSUE TITLE
Estrutura do Sass

### ISSUE THREAD

**Issue by 3runoDesign** [RubyCastsBrasil/RubyCastsBrasil#215]
Dei uma olhada aqui e vi que tudo basicamente é escrito na ```application.scss``` eu sugiro passar para uma organização melhor por ex.:
```shell
stylesheets/
|
|-- core/ # Estilo global e customização do grid
|
|-- helpers/ # @extend, @mixin e @functions. Tudo que necessariamente precisa ser "chamado"
|
|-- layouts/ # Estilo especifico de uma seção/pagina
|
|-- modules/ # Estilo dos componentes
|
|-- vendor/ # Lib. de terceiros
_variables.scss # Configuração das variaveis
application.scss
```
Ai no ```application.scss``` ficaria
```scss
# application.scss

@import "variables";
@import "helpers/*",
               "core/*",
               "modules/*",
               "layouts/*";
```
Fiz um pequeno post sobre isso - [Organizando projeto Sass](http://helabs.com/blog/2014/02/17/organizando-projeto-sass/)

**Comment by 3runoDesign** [comment]
Uma outra sugestão seria o uso do [Bourbon](bourbon.io), [Neat](neat.bourbon.io) e o [Bitters](bitters.bourbon.io). Olha esse post do **Mauro George** http://helabs.com/blog/2014/06/27/rails-front-end-com-bourbon-e-sua-familia/

**Comment by pragmaticivan** [comment]
Na verdade em application apenas é chamado o tree. Está bem modulado creio eu.

**Comment by plribeiro3000** [comment]
@3runoDesign Tu nao quer mandar um PR pra gente poder ver o antes e o depois e poder discutir em cima se for o caso?

**Comment by pragmaticivan** [comment]
Fechando por falta de atividade.
