### ISSUE TITLE
Sugestão para logotipo

### ISSUE THREAD

**Issue by 3runoDesign** [RubyCastsBrasil/RubyCastsBrasil#216]
Bem... eu ainda não sei como que está o andamento do design tal... enfim tenho uma sugestão para o logotipo. :)
![_rubycast](https://cloud.githubusercontent.com/assets/1563041/7421420/9df21732-ef5a-11e4-846e-503315d5cc36.png)

**Comment by plribeiro3000** [comment]
Wow. Bem maneiro @3runoDesign ! A gente tem uma discussão relacionada a isso na issue #48 .

Mas talvez o pessoal tenho algo a falar a respeito desse seu trabalho. =)

Ficou show de bola!

**Comment by joffilyfe** [comment]
@3runoDesign cara, parabéns. Ficou nem maneiro mesmo tua arte. Inclusive havendo ou não mudanças o que tu acha de marcarmos um fim de semana ai e finalizar-mos todas as issues relativas ao front-end?

**Comment by 3runoDesign** [comment]
@plribeiro3000 Vlw.
@joffilyfe vamos sim. Estou dando uma olhada geral aqui no projeto.

**Comment by pragmaticivan** [comment]
Porra ficou animal, hahaha já posso trocar lá no front-end? hahaha

**Comment by plribeiro3000** [comment]
@3runoDesign Tu mandar um PR com esse logotipo?

Tu vai ter que alterar [essa] pasta. Vlw!

**Comment by daniloisr** [comment]
@3runoDesign  Ficou muito bom cara :+1:

**Comment by lucasfurtado** [comment]
Muito bom @3runoDesign!

**Comment by 3runoDesign** [comment]
Blz vou fazer aqui.

**Comment by wenderjean** [comment]
@3runoDesign Show cara...

**Comment by rafex128** [comment]
@3runoDesign Ficou show.

**Comment by mfbmina** [comment]
Ficou bom pra caramba cara! Parabéns!

@plribeiro3000 a sua markdown não funcionou!

**Comment by plribeiro3000** [comment]
Acertei o markdown. Valeu @mfbmina !

**Comment by plribeiro3000** [comment]
@3runoDesign Tu poderia fazer o favor de atualizar a pasta [docs](https://github.com/RubyCastsBrasil/RubyCastsBrasil/tree/master/doc/logos) também?

Valeu!

**Comment by lccezinha** [comment]
Ficou foda! :D

**Comment by pragmaticivan** [comment]
Posso fechar essa issue? já subiu o PR?

**Comment by plribeiro3000** [comment]
Já! =)
